services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  frontend:
    # image: m4-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"